//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Data/Input/GameplayControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameplayControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameplayControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameplayControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""2ad43662-3feb-495f-aa94-a72cf27a8de2"",
            ""actions"": [
                {
                    ""name"": ""SwordAngle"",
                    ""type"": ""Value"",
                    ""id"": ""ea0ebc1b-614c-40aa-8617-977f3cd86f71"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Unsheathe"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5d1a124c-3ce0-4e74-ba96-d597ff5030bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PoseButtonTop"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ad2ed90e-bbbd-4e10-9b1d-da64921ae152"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PoseButtonMid"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f0f51208-706e-4519-ac55-3ea20dd7f47a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PoseButtonBot"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bcb9a1d1-8533-4521-8175-d407ea4c2913"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""39baa6a0-606b-4f77-b5c6-76ba86413d6d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99483b3e-11d8-47ec-a260-aeeb56d24426"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4344aec1-7de0-4426-92a9-9583499d8a68"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwordAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7672e99e-3ffc-42d9-be11-2fc2773cf926"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1d47cf3-9b37-4257-8024-c069bdbf27a6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea8ad47e-3250-4609-9cbc-b7b810563f7b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60b6bb79-ea8f-4a3e-8c0a-fee1c67c0324"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdfa374c-2849-4653-8808-cc191049aad4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90c6a19f-1311-4fc5-be5a-a70095e63343"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unsheathe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b4bc36a-da1f-4fa4-bf75-513c8bc65123"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a427325-233c-4d50-9742-7095554c5d87"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""976b9626-b55c-4f06-903d-8e36677aff94"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""947fe3b9-3c9f-4ae7-aa10-f1f0e31b9fad"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonTop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b023dbd5-7153-4450-a3da-c37d1394e4fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54fbbef0-de2a-4714-93b9-f890ce7d0815"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82732584-e272-43b9-8546-271728d6a558"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e560fdb-3ffc-40b3-af16-5fc70852789a"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1474649e-5823-424b-a1ff-dc1a32088e42"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""057cbf27-c811-460b-a77b-9bb162c2cfbf"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonMid"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b43bb2dc-8f77-472e-a011-bdee33c1c529"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59c731d5-778f-49c0-a3f8-1e749db33811"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""100cbe11-251a-4fe3-80ad-178f90c712e5"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bad70e17-a8c5-4fcf-963c-ff18dc31b3b1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseButtonBot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5428307-9e26-4ca5-b31f-d56d7ba965a8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gameplay"",
            ""bindingGroup"": ""Gameplay"",
            ""devices"": []
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_SwordAngle = m_Gameplay.FindAction("SwordAngle", throwIfNotFound: true);
        m_Gameplay_Unsheathe = m_Gameplay.FindAction("Unsheathe", throwIfNotFound: true);
        m_Gameplay_PoseButtonTop = m_Gameplay.FindAction("PoseButtonTop", throwIfNotFound: true);
        m_Gameplay_PoseButtonMid = m_Gameplay.FindAction("PoseButtonMid", throwIfNotFound: true);
        m_Gameplay_PoseButtonBot = m_Gameplay.FindAction("PoseButtonBot", throwIfNotFound: true);
        m_Gameplay_MousePos = m_Gameplay.FindAction("MousePos", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_SwordAngle;
    private readonly InputAction m_Gameplay_Unsheathe;
    private readonly InputAction m_Gameplay_PoseButtonTop;
    private readonly InputAction m_Gameplay_PoseButtonMid;
    private readonly InputAction m_Gameplay_PoseButtonBot;
    private readonly InputAction m_Gameplay_MousePos;
    public struct GameplayActions
    {
        private @GameplayControls m_Wrapper;
        public GameplayActions(@GameplayControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SwordAngle => m_Wrapper.m_Gameplay_SwordAngle;
        public InputAction @Unsheathe => m_Wrapper.m_Gameplay_Unsheathe;
        public InputAction @PoseButtonTop => m_Wrapper.m_Gameplay_PoseButtonTop;
        public InputAction @PoseButtonMid => m_Wrapper.m_Gameplay_PoseButtonMid;
        public InputAction @PoseButtonBot => m_Wrapper.m_Gameplay_PoseButtonBot;
        public InputAction @MousePos => m_Wrapper.m_Gameplay_MousePos;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @SwordAngle.started += instance.OnSwordAngle;
            @SwordAngle.performed += instance.OnSwordAngle;
            @SwordAngle.canceled += instance.OnSwordAngle;
            @Unsheathe.started += instance.OnUnsheathe;
            @Unsheathe.performed += instance.OnUnsheathe;
            @Unsheathe.canceled += instance.OnUnsheathe;
            @PoseButtonTop.started += instance.OnPoseButtonTop;
            @PoseButtonTop.performed += instance.OnPoseButtonTop;
            @PoseButtonTop.canceled += instance.OnPoseButtonTop;
            @PoseButtonMid.started += instance.OnPoseButtonMid;
            @PoseButtonMid.performed += instance.OnPoseButtonMid;
            @PoseButtonMid.canceled += instance.OnPoseButtonMid;
            @PoseButtonBot.started += instance.OnPoseButtonBot;
            @PoseButtonBot.performed += instance.OnPoseButtonBot;
            @PoseButtonBot.canceled += instance.OnPoseButtonBot;
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @SwordAngle.started -= instance.OnSwordAngle;
            @SwordAngle.performed -= instance.OnSwordAngle;
            @SwordAngle.canceled -= instance.OnSwordAngle;
            @Unsheathe.started -= instance.OnUnsheathe;
            @Unsheathe.performed -= instance.OnUnsheathe;
            @Unsheathe.canceled -= instance.OnUnsheathe;
            @PoseButtonTop.started -= instance.OnPoseButtonTop;
            @PoseButtonTop.performed -= instance.OnPoseButtonTop;
            @PoseButtonTop.canceled -= instance.OnPoseButtonTop;
            @PoseButtonMid.started -= instance.OnPoseButtonMid;
            @PoseButtonMid.performed -= instance.OnPoseButtonMid;
            @PoseButtonMid.canceled -= instance.OnPoseButtonMid;
            @PoseButtonBot.started -= instance.OnPoseButtonBot;
            @PoseButtonBot.performed -= instance.OnPoseButtonBot;
            @PoseButtonBot.canceled -= instance.OnPoseButtonBot;
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_GameplaySchemeIndex = -1;
    public InputControlScheme GameplayScheme
    {
        get
        {
            if (m_GameplaySchemeIndex == -1) m_GameplaySchemeIndex = asset.FindControlSchemeIndex("Gameplay");
            return asset.controlSchemes[m_GameplaySchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnSwordAngle(InputAction.CallbackContext context);
        void OnUnsheathe(InputAction.CallbackContext context);
        void OnPoseButtonTop(InputAction.CallbackContext context);
        void OnPoseButtonMid(InputAction.CallbackContext context);
        void OnPoseButtonBot(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
    }
}
